### PR TITLE
add storybook

### PR DESCRIPTION
**Pull request by annavlz**
Click merge pull request. After that on our machine on branch master run "git pull", then "npm run install", then "npm run storybook"
more about React and Stroybook here https://storybook.js.org/docs/guides/guide-react/#step-4-write-your-stories

### CODE REVIEW

**Comment by ChrisKirbyDev** [comment]
Hi Anna,

Currently getting a lot of errors when running npm run storybook, Multiple
module error alarms. Not exactly sure what is going on.

Kind Regards

Chris

**Comment by annavlz** [comment]
Have you run npm install before running storybook?

**Comment by ChrisKirbyDev** [comment]
If i run that command i get,

$ npm run install
npm ERR! missing script: install

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\chris\AppData\Roaming\npm-cache\_logs\2020-07-13T01_49_38_701Z-debug.log

So i used npm install.

**Comment by ChrisKirbyDev** [comment]
Hi Anna,

Looks like i have resolved the issue. The path through react was hardcoding
the path. So i removed the ./node-modules/react to "react";

I will push that now

**Comment by annavlz** [comment]
Sorry , my fault! just typed automatically.
The comand is _**npm install**_.  to install all the libraries from package.json
yes,this is **./node-modules/react** strange, it should be "react"

Does it work now?

And the RADME.md - it was an example, that's why it was a draft PR. You need to create your own with all the details. And choose which scenario (there are two options I suggested).

**Comment by ChrisKirbyDev** [comment]
Hi Anna,

no worries, always good practice! Okay i will have a look at the readme,
just working on the Navbar currently!

**Pull request merged**
