### PR TITLE
Header

### PR DESCRIPTION
**Pull request by ChrisKirbyDev**
Import background header image, styled background image in CSS.
styled consultation button in the header.
refractor CSS and restyle font and adjusted font placement.
setup portfolio.js with HTML and class names.

### CODE REVIEW

**Comment by annavlz** [comment]
I recommend not to use React classes, and use functions instead. https://www.robinwieruch.de/react-function-component

**Comment by annavlz** [comment]
For CSS looks at this https://css-tricks.com/guides/layout/

**Comment by annavlz** [comment]
and this https://blog.bitsrc.io/5-ways-to-style-react-components-in-2019-30f1ccc2b5b

**Comment by ChrisKirbyDev** [comment]
Hi,

Thank you, will give these a good read this evening. I will stop using
class as my default go-to template, Currently working on an image scroller
at the moment for the portfolio.

Kind Regards

Chris Kirby

**Comment by ChrisKirbyDev** [comment]
Hi Anna,

Just an FYI, I will be away in Queenstown from this Friday evening until
next Sunday. Would you like to have a chat at all, or does everything seem
to be going well from your end?

kind regards

Chris

**Pull request merged**
